import { useLingui } from '@lingui/react/macro'
import type { Language } from '@/library/languages'

/** The languages books can be preferred in, named in the listener's language. */
export function useLanguageNames(): Record<Language, string> {
  const { t } = useLingui()

  return {
    en: t({ message: 'English', comment: 'A language books can be preferred in' }),
    sv: t({ message: 'Swedish', comment: 'A language books can be preferred in' }),
    es: t({ message: 'Spanish', comment: 'A language books can be preferred in' }),
    de: t({ message: 'German', comment: 'A language books can be preferred in' }),
    fr: t({ message: 'French', comment: 'A language books can be preferred in' }),
    it: t({ message: 'Italian', comment: 'A language books can be preferred in' }),
    pt: t({ message: 'Portuguese', comment: 'A language books can be preferred in' }),
    nl: t({ message: 'Dutch', comment: 'A language books can be preferred in' }),
    da: t({ message: 'Danish', comment: 'A language books can be preferred in' }),
    no: t({ message: 'Norwegian', comment: 'A language books can be preferred in' }),
    fi: t({ message: 'Finnish', comment: 'A language books can be preferred in' }),
    is: t({ message: 'Icelandic', comment: 'A language books can be preferred in' }),
    pl: t({ message: 'Polish', comment: 'A language books can be preferred in' }),
    cs: t({ message: 'Czech', comment: 'A language books can be preferred in' }),
    sk: t({ message: 'Slovak', comment: 'A language books can be preferred in' }),
    hu: t({ message: 'Hungarian', comment: 'A language books can be preferred in' }),
    ro: t({ message: 'Romanian', comment: 'A language books can be preferred in' }),
    bg: t({ message: 'Bulgarian', comment: 'A language books can be preferred in' }),
    el: t({ message: 'Greek', comment: 'A language books can be preferred in' }),
    tr: t({ message: 'Turkish', comment: 'A language books can be preferred in' }),
    ru: t({ message: 'Russian', comment: 'A language books can be preferred in' }),
    uk: t({ message: 'Ukrainian', comment: 'A language books can be preferred in' }),
    sr: t({ message: 'Serbian', comment: 'A language books can be preferred in' }),
    hr: t({ message: 'Croatian', comment: 'A language books can be preferred in' }),
    sl: t({ message: 'Slovenian', comment: 'A language books can be preferred in' }),
    et: t({ message: 'Estonian', comment: 'A language books can be preferred in' }),
    lv: t({ message: 'Latvian', comment: 'A language books can be preferred in' }),
    lt: t({ message: 'Lithuanian', comment: 'A language books can be preferred in' }),
    ca: t({ message: 'Catalan', comment: 'A language books can be preferred in' }),
    eu: t({ message: 'Basque', comment: 'A language books can be preferred in' }),
    gl: t({ message: 'Galician', comment: 'A language books can be preferred in' }),
    ga: t({ message: 'Irish', comment: 'A language books can be preferred in' }),
    cy: t({ message: 'Welsh', comment: 'A language books can be preferred in' }),
    af: t({ message: 'Afrikaans', comment: 'A language books can be preferred in' }),
    ar: t({ message: 'Arabic', comment: 'A language books can be preferred in' }),
    he: t({ message: 'Hebrew', comment: 'A language books can be preferred in' }),
    fa: t({ message: 'Persian', comment: 'A language books can be preferred in' }),
    hi: t({ message: 'Hindi', comment: 'A language books can be preferred in' }),
    bn: t({ message: 'Bengali', comment: 'A language books can be preferred in' }),
    ur: t({ message: 'Urdu', comment: 'A language books can be preferred in' }),
    id: t({ message: 'Indonesian', comment: 'A language books can be preferred in' }),
    ms: t({ message: 'Malay', comment: 'A language books can be preferred in' }),
    vi: t({ message: 'Vietnamese', comment: 'A language books can be preferred in' }),
    th: t({ message: 'Thai', comment: 'A language books can be preferred in' }),
    tl: t({ message: 'Tagalog', comment: 'A language books can be preferred in' }),
    zh: t({ message: 'Chinese', comment: 'A language books can be preferred in' }),
    ja: t({ message: 'Japanese', comment: 'A language books can be preferred in' }),
    ko: t({ message: 'Korean', comment: 'A language books can be preferred in' }),
    sw: t({ message: 'Swahili', comment: 'A language books can be preferred in' }),
    eo: t({ message: 'Esperanto', comment: 'A language books can be preferred in' }),
    la: t({ message: 'Latin', comment: 'A language books can be preferred in' }),
  }
}
